[package]
name = "blake3ruby"
version = "0.1.0"
edition = "2021"
authors = ["Nightforge <modo00@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.5.2" }
hex = { version = "0.4.3" }
blake3 = "1.3.3"
