module Blake3ruby
  VERSION: String
end

module Digest
  module Blake3
    def self.hexdigest(subject: String) -> String
    def self.derive_key(context: String, key: String) -> String

    class Hasher
      def self.new: () -> Digest::Blake3::Hasher
      def update: (subject: String) -> Digest::Blake3::Hasher
      def finalize: () -> String
    end
  end
end
